name: fetchify
description: "A Screenshots Manager."

publish_to: "none"

# The patch version numbering is automatically incremented by the git hook.
# Only update major and minor versions manually.
version: 1.9.51+6

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  sentry_flutter: ^8.14.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  uuid: ^4.5.1
  intl: ^0.20.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  image: ^4.1.3
  http: ^1.4.0
  shared_preferences: ^2.0.15
  package_info_plus: ^8.3.0
  share_plus: ^11.0.0
  flutter_local_notifications: ^17.2.1
  dynamic_color: ^1.7.0
  animations: ^2.0.11
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.3.0
  posthog_flutter: ^4.0.0
  file_picker: ^8.1.5
  tesseract_ocr: ^0.5.0
  flutter_gemma: ^0.10.0
  wakelock_plus: ^1.2.8
  timezone: ^0.9.4
  battery_plus: ^6.0.2
  connectivity_plus: ^6.0.5

dev_dependencies:
  sentry_dart_plugin: ^2.4.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/icon/ic_launcher_foreground.png"
  adaptive_icon_monochrome: "assets/icon/ic_launcher_monochrome.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icon/
    - assets/tessdata_config.json
    - assets/tessdata/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-BoldItalic.ttf
          weight: 700
          style: italic

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: shots-studio
